// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeManagerWeb.Data;

#nullable disable

namespace RecipeManagerWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220805134840_Seed Data")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("RecipeManagerWeb.Models.GroceryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroceryCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Obst und Gemüse"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Frische und Kühlung"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tiefkühl"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nahrungsmittel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gewürze"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Süßes und Salziges"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kaffee, Tee & Kakao"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Getränke"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Wein & Spirituosen"
                        });
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.GroceryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroceryCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroceryCategoryId");

                    b.ToTable("GroceryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroceryCategoryId = 1,
                            Name = "Ananas"
                        },
                        new
                        {
                            Id = 2,
                            GroceryCategoryId = 1,
                            Name = "Apfel"
                        },
                        new
                        {
                            Id = 3,
                            GroceryCategoryId = 1,
                            Name = "Apfelsine"
                        },
                        new
                        {
                            Id = 4,
                            GroceryCategoryId = 1,
                            Name = "Aprikose"
                        },
                        new
                        {
                            Id = 5,
                            GroceryCategoryId = 1,
                            Name = "Aubergine"
                        },
                        new
                        {
                            Id = 6,
                            GroceryCategoryId = 1,
                            Name = "Banane"
                        },
                        new
                        {
                            Id = 7,
                            GroceryCategoryId = 1,
                            Name = "Birne"
                        },
                        new
                        {
                            Id = 8,
                            GroceryCategoryId = 1,
                            Name = "Blattsalat"
                        },
                        new
                        {
                            Id = 9,
                            GroceryCategoryId = 1,
                            Name = "Blaubeeren"
                        },
                        new
                        {
                            Id = 10,
                            GroceryCategoryId = 1,
                            Name = "Blumenkohl"
                        },
                        new
                        {
                            Id = 11,
                            GroceryCategoryId = 1,
                            Name = "Brokkoli"
                        },
                        new
                        {
                            Id = 12,
                            GroceryCategoryId = 1,
                            Name = "Brombeere"
                        },
                        new
                        {
                            Id = 13,
                            GroceryCategoryId = 1,
                            Name = "Clementine"
                        },
                        new
                        {
                            Id = 14,
                            GroceryCategoryId = 1,
                            Name = "Cranberries"
                        },
                        new
                        {
                            Id = 15,
                            GroceryCategoryId = 1,
                            Name = "Dattel"
                        },
                        new
                        {
                            Id = 16,
                            GroceryCategoryId = 1,
                            Name = "Drachenfrucht"
                        },
                        new
                        {
                            Id = 17,
                            GroceryCategoryId = 1,
                            Name = "Eisbergsalat"
                        },
                        new
                        {
                            Id = 18,
                            GroceryCategoryId = 1,
                            Name = "Erbse"
                        },
                        new
                        {
                            Id = 19,
                            GroceryCategoryId = 1,
                            Name = "Erdbeere"
                        },
                        new
                        {
                            Id = 20,
                            GroceryCategoryId = 1,
                            Name = "Feige"
                        },
                        new
                        {
                            Id = 21,
                            GroceryCategoryId = 1,
                            Name = "Feldsalat"
                        },
                        new
                        {
                            Id = 22,
                            GroceryCategoryId = 1,
                            Name = "Fenchel"
                        },
                        new
                        {
                            Id = 23,
                            GroceryCategoryId = 1,
                            Name = "Granatapfel"
                        },
                        new
                        {
                            Id = 24,
                            GroceryCategoryId = 1,
                            Name = "Grapefruit"
                        },
                        new
                        {
                            Id = 25,
                            GroceryCategoryId = 1,
                            Name = "Grünkohl"
                        },
                        new
                        {
                            Id = 26,
                            GroceryCategoryId = 1,
                            Name = "Guave"
                        },
                        new
                        {
                            Id = 27,
                            GroceryCategoryId = 1,
                            Name = "Gurke"
                        },
                        new
                        {
                            Id = 28,
                            GroceryCategoryId = 1,
                            Name = "Hagebutte"
                        },
                        new
                        {
                            Id = 29,
                            GroceryCategoryId = 1,
                            Name = "Heidelbeere"
                        },
                        new
                        {
                            Id = 30,
                            GroceryCategoryId = 1,
                            Name = "Himbeere"
                        },
                        new
                        {
                            Id = 31,
                            GroceryCategoryId = 1,
                            Name = "Holunderbeere"
                        },
                        new
                        {
                            Id = 32,
                            GroceryCategoryId = 1,
                            Name = "Honigmelone"
                        },
                        new
                        {
                            Id = 33,
                            GroceryCategoryId = 1,
                            Name = "Ingwer"
                        },
                        new
                        {
                            Id = 34,
                            GroceryCategoryId = 1,
                            Name = "Johannisbeere"
                        },
                        new
                        {
                            Id = 35,
                            GroceryCategoryId = 1,
                            Name = "Kaki"
                        },
                        new
                        {
                            Id = 36,
                            GroceryCategoryId = 1,
                            Name = "Kaktusfeige"
                        },
                        new
                        {
                            Id = 37,
                            GroceryCategoryId = 1,
                            Name = "Kartoffeln"
                        },
                        new
                        {
                            Id = 38,
                            GroceryCategoryId = 1,
                            Name = "Kirsche"
                        },
                        new
                        {
                            Id = 39,
                            GroceryCategoryId = 1,
                            Name = "Kiwi"
                        },
                        new
                        {
                            Id = 40,
                            GroceryCategoryId = 1,
                            Name = "Knoblauch"
                        },
                        new
                        {
                            Id = 41,
                            GroceryCategoryId = 1,
                            Name = "Kohlrabi"
                        },
                        new
                        {
                            Id = 42,
                            GroceryCategoryId = 1,
                            Name = "Kohlrübe"
                        },
                        new
                        {
                            Id = 43,
                            GroceryCategoryId = 1,
                            Name = "Kokosnuss"
                        },
                        new
                        {
                            Id = 44,
                            GroceryCategoryId = 1,
                            Name = "Kürbis"
                        },
                        new
                        {
                            Id = 45,
                            GroceryCategoryId = 1,
                            Name = "Lauchzwiebeln"
                        },
                        new
                        {
                            Id = 46,
                            GroceryCategoryId = 1,
                            Name = "Limette"
                        },
                        new
                        {
                            Id = 47,
                            GroceryCategoryId = 1,
                            Name = "Linsen"
                        },
                        new
                        {
                            Id = 48,
                            GroceryCategoryId = 1,
                            Name = "Litschi"
                        },
                        new
                        {
                            Id = 49,
                            GroceryCategoryId = 1,
                            Name = "Mandarine"
                        },
                        new
                        {
                            Id = 50,
                            GroceryCategoryId = 1,
                            Name = "Mango"
                        },
                        new
                        {
                            Id = 51,
                            GroceryCategoryId = 1,
                            Name = "Maracuja"
                        },
                        new
                        {
                            Id = 52,
                            GroceryCategoryId = 1,
                            Name = "Melonen"
                        },
                        new
                        {
                            Id = 53,
                            GroceryCategoryId = 1,
                            Name = "Mirabelle"
                        },
                        new
                        {
                            Id = 54,
                            GroceryCategoryId = 1,
                            Name = "Möhre"
                        },
                        new
                        {
                            Id = 55,
                            GroceryCategoryId = 1,
                            Name = "Nektarine"
                        },
                        new
                        {
                            Id = 56,
                            GroceryCategoryId = 1,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 57,
                            GroceryCategoryId = 1,
                            Name = "Pampelmuse"
                        },
                        new
                        {
                            Id = 58,
                            GroceryCategoryId = 1,
                            Name = "Papaya"
                        },
                        new
                        {
                            Id = 59,
                            GroceryCategoryId = 1,
                            Name = "Paprika"
                        },
                        new
                        {
                            Id = 60,
                            GroceryCategoryId = 1,
                            Name = "Passionsfrucht"
                        },
                        new
                        {
                            Id = 61,
                            GroceryCategoryId = 1,
                            Name = "Pastinake"
                        },
                        new
                        {
                            Id = 62,
                            GroceryCategoryId = 1,
                            Name = "Petersilie"
                        },
                        new
                        {
                            Id = 63,
                            GroceryCategoryId = 1,
                            Name = "Pfirsich"
                        },
                        new
                        {
                            Id = 64,
                            GroceryCategoryId = 1,
                            Name = "Pflaume"
                        },
                        new
                        {
                            Id = 65,
                            GroceryCategoryId = 1,
                            Name = "Physalis"
                        },
                        new
                        {
                            Id = 66,
                            GroceryCategoryId = 1,
                            Name = "Porree"
                        },
                        new
                        {
                            Id = 67,
                            GroceryCategoryId = 1,
                            Name = "Preiselbeere"
                        },
                        new
                        {
                            Id = 68,
                            GroceryCategoryId = 1,
                            Name = "Puffbohnen"
                        },
                        new
                        {
                            Id = 69,
                            GroceryCategoryId = 1,
                            Name = "Quitte"
                        },
                        new
                        {
                            Id = 70,
                            GroceryCategoryId = 1,
                            Name = "Radieschen"
                        },
                        new
                        {
                            Id = 71,
                            GroceryCategoryId = 1,
                            Name = "Rettich"
                        },
                        new
                        {
                            Id = 72,
                            GroceryCategoryId = 1,
                            Name = "Rhabarber"
                        },
                        new
                        {
                            Id = 73,
                            GroceryCategoryId = 1,
                            Name = "Rote Rübe"
                        },
                        new
                        {
                            Id = 74,
                            GroceryCategoryId = 1,
                            Name = "Rotkohl"
                        },
                        new
                        {
                            Id = 75,
                            GroceryCategoryId = 1,
                            Name = "Salatgurke"
                        },
                        new
                        {
                            Id = 76,
                            GroceryCategoryId = 1,
                            Name = "Sanddornbeere"
                        },
                        new
                        {
                            Id = 77,
                            GroceryCategoryId = 1,
                            Name = "Sauerkirsche"
                        },
                        new
                        {
                            Id = 78,
                            GroceryCategoryId = 1,
                            Name = "Schalotten"
                        },
                        new
                        {
                            Id = 79,
                            GroceryCategoryId = 1,
                            Name = "Schnittlauch"
                        },
                        new
                        {
                            Id = 80,
                            GroceryCategoryId = 1,
                            Name = "Sellerie"
                        },
                        new
                        {
                            Id = 81,
                            GroceryCategoryId = 1,
                            Name = "Sojabohnen"
                        },
                        new
                        {
                            Id = 82,
                            GroceryCategoryId = 1,
                            Name = "Spinat"
                        },
                        new
                        {
                            Id = 83,
                            GroceryCategoryId = 1,
                            Name = "Stachelbeere"
                        },
                        new
                        {
                            Id = 84,
                            GroceryCategoryId = 1,
                            Name = "Suppengrün"
                        },
                        new
                        {
                            Id = 85,
                            GroceryCategoryId = 1,
                            Name = "Süßkartoffeln"
                        },
                        new
                        {
                            Id = 86,
                            GroceryCategoryId = 1,
                            Name = "Süßkirsche"
                        },
                        new
                        {
                            Id = 87,
                            GroceryCategoryId = 1,
                            Name = "Tomate"
                        },
                        new
                        {
                            Id = 88,
                            GroceryCategoryId = 1,
                            Name = "Tomate (klein)"
                        },
                        new
                        {
                            Id = 89,
                            GroceryCategoryId = 1,
                            Name = "Traube"
                        },
                        new
                        {
                            Id = 90,
                            GroceryCategoryId = 1,
                            Name = "Wassermelone"
                        },
                        new
                        {
                            Id = 91,
                            GroceryCategoryId = 1,
                            Name = "Weintraube"
                        },
                        new
                        {
                            Id = 92,
                            GroceryCategoryId = 1,
                            Name = "Weißkohl"
                        },
                        new
                        {
                            Id = 93,
                            GroceryCategoryId = 1,
                            Name = "Zitrone"
                        },
                        new
                        {
                            Id = 94,
                            GroceryCategoryId = 1,
                            Name = "Zucchini"
                        },
                        new
                        {
                            Id = 95,
                            GroceryCategoryId = 1,
                            Name = "Zuckermelone"
                        },
                        new
                        {
                            Id = 96,
                            GroceryCategoryId = 1,
                            Name = "Zwetschge"
                        },
                        new
                        {
                            Id = 97,
                            GroceryCategoryId = 1,
                            Name = "Zwiebel"
                        },
                        new
                        {
                            Id = 98,
                            GroceryCategoryId = 2,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 99,
                            GroceryCategoryId = 2,
                            Name = "Camembert"
                        },
                        new
                        {
                            Id = 100,
                            GroceryCategoryId = 2,
                            Name = "Creme Fraiche"
                        },
                        new
                        {
                            Id = 101,
                            GroceryCategoryId = 2,
                            Name = "Eier"
                        },
                        new
                        {
                            Id = 102,
                            GroceryCategoryId = 2,
                            Name = "Feta"
                        },
                        new
                        {
                            Id = 103,
                            GroceryCategoryId = 2,
                            Name = "Fettarmer Joghurt"
                        },
                        new
                        {
                            Id = 104,
                            GroceryCategoryId = 2,
                            Name = "Frischkäse"
                        },
                        new
                        {
                            Id = 105,
                            GroceryCategoryId = 2,
                            Name = "Gouda"
                        },
                        new
                        {
                            Id = 106,
                            GroceryCategoryId = 2,
                            Name = "Griechischer Joghurt"
                        },
                        new
                        {
                            Id = 107,
                            GroceryCategoryId = 2,
                            Name = "Gyros"
                        },
                        new
                        {
                            Id = 108,
                            GroceryCategoryId = 2,
                            Name = "Hackfleisch"
                        },
                        new
                        {
                            Id = 109,
                            GroceryCategoryId = 2,
                            Name = "Hänchenbrustfilet"
                        },
                        new
                        {
                            Id = 110,
                            GroceryCategoryId = 2,
                            Name = "Hänchenschenkel"
                        },
                        new
                        {
                            Id = 111,
                            GroceryCategoryId = 2,
                            Name = "Joghurt"
                        },
                        new
                        {
                            Id = 112,
                            GroceryCategoryId = 2,
                            Name = "Kefir"
                        },
                        new
                        {
                            Id = 113,
                            GroceryCategoryId = 2,
                            Name = "Kochschinken"
                        },
                        new
                        {
                            Id = 114,
                            GroceryCategoryId = 2,
                            Name = "Kräuterquark"
                        },
                        new
                        {
                            Id = 115,
                            GroceryCategoryId = 2,
                            Name = "Milch 1.5%"
                        },
                        new
                        {
                            Id = 116,
                            GroceryCategoryId = 2,
                            Name = "Milch 3.5%"
                        },
                        new
                        {
                            Id = 117,
                            GroceryCategoryId = 2,
                            Name = "Mozarelle"
                        },
                        new
                        {
                            Id = 118,
                            GroceryCategoryId = 2,
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Id = 119,
                            GroceryCategoryId = 2,
                            Name = "Quark Halbfettstufe"
                        },
                        new
                        {
                            Id = 120,
                            GroceryCategoryId = 2,
                            Name = "Räucher-Lachs"
                        },
                        new
                        {
                            Id = 121,
                            GroceryCategoryId = 2,
                            Name = "Salami"
                        },
                        new
                        {
                            Id = 122,
                            GroceryCategoryId = 2,
                            Name = "Schinken"
                        },
                        new
                        {
                            Id = 123,
                            GroceryCategoryId = 2,
                            Name = "Schlagsahne"
                        },
                        new
                        {
                            Id = 124,
                            GroceryCategoryId = 2,
                            Name = "Schlagssahne"
                        },
                        new
                        {
                            Id = 125,
                            GroceryCategoryId = 2,
                            Name = "Schmand"
                        },
                        new
                        {
                            Id = 126,
                            GroceryCategoryId = 2,
                            Name = "Speisequark Magerstufe"
                        },
                        new
                        {
                            Id = 127,
                            GroceryCategoryId = 2,
                            Name = "Süßrahmbutter"
                        },
                        new
                        {
                            Id = 128,
                            GroceryCategoryId = 2,
                            Name = "Wiener Würstchen"
                        },
                        new
                        {
                            Id = 129,
                            GroceryCategoryId = 3,
                            Name = "Shrimps"
                        },
                        new
                        {
                            Id = 130,
                            GroceryCategoryId = 4,
                            Name = "Backin"
                        },
                        new
                        {
                            Id = 131,
                            GroceryCategoryId = 4,
                            Name = "Basmati Reis"
                        },
                        new
                        {
                            Id = 132,
                            GroceryCategoryId = 4,
                            Name = "Bourbon-Vanillezucker"
                        },
                        new
                        {
                            Id = 133,
                            GroceryCategoryId = 4,
                            Name = "Brauner Zucker"
                        },
                        new
                        {
                            Id = 134,
                            GroceryCategoryId = 4,
                            Name = "Couscous"
                        },
                        new
                        {
                            Id = 135,
                            GroceryCategoryId = 4,
                            Name = "Dinkelmehl Type 630"
                        },
                        new
                        {
                            Id = 136,
                            GroceryCategoryId = 4,
                            Name = "Dinkel-Vollkornmehl"
                        },
                        new
                        {
                            Id = 137,
                            GroceryCategoryId = 4,
                            Name = "Essig"
                        },
                        new
                        {
                            Id = 138,
                            GroceryCategoryId = 4,
                            Name = "Fusilli"
                        },
                        new
                        {
                            Id = 139,
                            GroceryCategoryId = 4,
                            Name = "Gemüsebrühe"
                        },
                        new
                        {
                            Id = 140,
                            GroceryCategoryId = 4,
                            Name = "Gnocchi"
                        },
                        new
                        {
                            Id = 141,
                            GroceryCategoryId = 4,
                            Name = "Grießbrei"
                        },
                        new
                        {
                            Id = 142,
                            GroceryCategoryId = 4,
                            Name = "Haferflocken"
                        },
                        new
                        {
                            Id = 143,
                            GroceryCategoryId = 4,
                            Name = "Hefe"
                        },
                        new
                        {
                            Id = 144,
                            GroceryCategoryId = 4,
                            Name = "Hörnchennudeln"
                        },
                        new
                        {
                            Id = 145,
                            GroceryCategoryId = 4,
                            Name = "Hühnerbrühe"
                        },
                        new
                        {
                            Id = 146,
                            GroceryCategoryId = 4,
                            Name = "Ketchup"
                        },
                        new
                        {
                            Id = 147,
                            GroceryCategoryId = 4,
                            Name = "Kicherebsen"
                        },
                        new
                        {
                            Id = 148,
                            GroceryCategoryId = 4,
                            Name = "Kidney-Bohnen"
                        },
                        new
                        {
                            Id = 149,
                            GroceryCategoryId = 4,
                            Name = "Kokosraspel"
                        },
                        new
                        {
                            Id = 150,
                            GroceryCategoryId = 4,
                            Name = "Lasagne"
                        },
                        new
                        {
                            Id = 151,
                            GroceryCategoryId = 4,
                            Name = "Mais"
                        },
                        new
                        {
                            Id = 152,
                            GroceryCategoryId = 4,
                            Name = "Mandeln"
                        },
                        new
                        {
                            Id = 153,
                            GroceryCategoryId = 4,
                            Name = "Milchreis"
                        },
                        new
                        {
                            Id = 154,
                            GroceryCategoryId = 4,
                            Name = "Natron"
                        },
                        new
                        {
                            Id = 155,
                            GroceryCategoryId = 4,
                            Name = "Olivenöl"
                        },
                        new
                        {
                            Id = 156,
                            GroceryCategoryId = 4,
                            Name = "Penne Rigate"
                        },
                        new
                        {
                            Id = 157,
                            GroceryCategoryId = 4,
                            Name = "Pesto alla Genovese"
                        },
                        new
                        {
                            Id = 158,
                            GroceryCategoryId = 4,
                            Name = "Pesto Rosto"
                        },
                        new
                        {
                            Id = 159,
                            GroceryCategoryId = 4,
                            Name = "Puderzucker"
                        },
                        new
                        {
                            Id = 160,
                            GroceryCategoryId = 4,
                            Name = "Reis"
                        },
                        new
                        {
                            Id = 161,
                            GroceryCategoryId = 4,
                            Name = "Rote Linsen"
                        },
                        new
                        {
                            Id = 162,
                            GroceryCategoryId = 4,
                            Name = "Sahnesteif"
                        },
                        new
                        {
                            Id = 163,
                            GroceryCategoryId = 4,
                            Name = "Salz"
                        },
                        new
                        {
                            Id = 164,
                            GroceryCategoryId = 4,
                            Name = "Schokoladen-Kuverüte"
                        },
                        new
                        {
                            Id = 165,
                            GroceryCategoryId = 4,
                            Name = "Senf"
                        },
                        new
                        {
                            Id = 166,
                            GroceryCategoryId = 4,
                            Name = "Sonnenblumenöl"
                        },
                        new
                        {
                            Id = 167,
                            GroceryCategoryId = 4,
                            Name = "Spaghetti"
                        },
                        new
                        {
                            Id = 168,
                            GroceryCategoryId = 4,
                            Name = "Speisestärke"
                        },
                        new
                        {
                            Id = 169,
                            GroceryCategoryId = 4,
                            Name = "Spitzen-Langkorn-Reis"
                        },
                        new
                        {
                            Id = 170,
                            GroceryCategoryId = 4,
                            Name = "Suppennudeln"
                        },
                        new
                        {
                            Id = 171,
                            GroceryCategoryId = 4,
                            Name = "Tomaten passiert"
                        },
                        new
                        {
                            Id = 172,
                            GroceryCategoryId = 4,
                            Name = "Tomatenmark"
                        },
                        new
                        {
                            Id = 173,
                            GroceryCategoryId = 4,
                            Name = "Tortenguss"
                        },
                        new
                        {
                            Id = 174,
                            GroceryCategoryId = 4,
                            Name = "Vanilin"
                        },
                        new
                        {
                            Id = 175,
                            GroceryCategoryId = 4,
                            Name = "Weißbroattoast"
                        },
                        new
                        {
                            Id = 176,
                            GroceryCategoryId = 4,
                            Name = "Weizenmehl 405"
                        },
                        new
                        {
                            Id = 177,
                            GroceryCategoryId = 4,
                            Name = "Zartbitter-Kuvetüre"
                        },
                        new
                        {
                            Id = 178,
                            GroceryCategoryId = 4,
                            Name = "Zucker"
                        },
                        new
                        {
                            Id = 179,
                            GroceryCategoryId = 5,
                            Name = "Basilikum gerebelt"
                        },
                        new
                        {
                            Id = 180,
                            GroceryCategoryId = 5,
                            Name = "Bohnenkraut"
                        },
                        new
                        {
                            Id = 181,
                            GroceryCategoryId = 5,
                            Name = "Chili"
                        },
                        new
                        {
                            Id = 182,
                            GroceryCategoryId = 5,
                            Name = "Curry"
                        },
                        new
                        {
                            Id = 183,
                            GroceryCategoryId = 5,
                            Name = "Curry gemahlen"
                        },
                        new
                        {
                            Id = 184,
                            GroceryCategoryId = 5,
                            Name = "Dillspitzen"
                        },
                        new
                        {
                            Id = 185,
                            GroceryCategoryId = 5,
                            Name = "Kardamon"
                        },
                        new
                        {
                            Id = 186,
                            GroceryCategoryId = 5,
                            Name = "Knoblauch granuliert"
                        },
                        new
                        {
                            Id = 187,
                            GroceryCategoryId = 5,
                            Name = "Koriander gemahlen"
                        },
                        new
                        {
                            Id = 188,
                            GroceryCategoryId = 5,
                            Name = "Kreuzkümmel gemahlen"
                        },
                        new
                        {
                            Id = 189,
                            GroceryCategoryId = 5,
                            Name = "Kurkuma gemahlen"
                        },
                        new
                        {
                            Id = 190,
                            GroceryCategoryId = 5,
                            Name = "Loorbeerblätter"
                        },
                        new
                        {
                            Id = 191,
                            GroceryCategoryId = 5,
                            Name = "Majoran gerebelt"
                        },
                        new
                        {
                            Id = 192,
                            GroceryCategoryId = 5,
                            Name = "Muskatnuss"
                        },
                        new
                        {
                            Id = 193,
                            GroceryCategoryId = 5,
                            Name = "Oregano gerebelt"
                        },
                        new
                        {
                            Id = 194,
                            GroceryCategoryId = 5,
                            Name = "Paprika Edelsüß"
                        },
                        new
                        {
                            Id = 195,
                            GroceryCategoryId = 5,
                            Name = "Paprika Rosenscharf"
                        },
                        new
                        {
                            Id = 196,
                            GroceryCategoryId = 5,
                            Name = "Rosmarin"
                        },
                        new
                        {
                            Id = 197,
                            GroceryCategoryId = 5,
                            Name = "Thymian gerebelt"
                        },
                        new
                        {
                            Id = 198,
                            GroceryCategoryId = 5,
                            Name = "Zimt gemahlen"
                        },
                        new
                        {
                            Id = 199,
                            GroceryCategoryId = 5,
                            Name = "Zimtstangen"
                        },
                        new
                        {
                            Id = 200,
                            GroceryCategoryId = 6,
                            Name = "Walnüsse"
                        },
                        new
                        {
                            Id = 201,
                            GroceryCategoryId = 6,
                            Name = "Cashewkerne"
                        },
                        new
                        {
                            Id = 202,
                            GroceryCategoryId = 6,
                            Name = "Pistazien"
                        },
                        new
                        {
                            Id = 203,
                            GroceryCategoryId = 6,
                            Name = "Paranusskerne"
                        },
                        new
                        {
                            Id = 204,
                            GroceryCategoryId = 6,
                            Name = "Maronen"
                        },
                        new
                        {
                            Id = 205,
                            GroceryCategoryId = 6,
                            Name = "Macadamia"
                        },
                        new
                        {
                            Id = 206,
                            GroceryCategoryId = 6,
                            Name = "Pekannusskerne"
                        },
                        new
                        {
                            Id = 207,
                            GroceryCategoryId = 7,
                            Name = "Kondensmilch"
                        },
                        new
                        {
                            Id = 208,
                            GroceryCategoryId = 7,
                            Name = "Kokosmilch"
                        },
                        new
                        {
                            Id = 209,
                            GroceryCategoryId = 7,
                            Name = "Grüner Tee"
                        },
                        new
                        {
                            Id = 210,
                            GroceryCategoryId = 8,
                            Name = "Apfelsaft"
                        },
                        new
                        {
                            Id = 211,
                            GroceryCategoryId = 8,
                            Name = "Kirschsaft"
                        },
                        new
                        {
                            Id = 212,
                            GroceryCategoryId = 9,
                            Name = "Rotwein"
                        });
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.InstructionStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("InstructionSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecipeId = 1,
                            Text = "step 1"
                        },
                        new
                        {
                            Id = 2,
                            RecipeId = 1,
                            Text = "step 2"
                        },
                        new
                        {
                            Id = 3,
                            RecipeId = 1,
                            Text = "step 3"
                        },
                        new
                        {
                            Id = 4,
                            RecipeId = 2,
                            Text = "step 1"
                        });
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PortionUnit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Vegetarian")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2.0,
                            Comment = "Dont' add to much water",
                            PortionUnit = 2,
                            RecipeCategoryId = 1,
                            Source = "Book xyz",
                            Time = 120,
                            Title = "Example recipe 1",
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 2,
                            Amount = 4.0,
                            PortionUnit = 3,
                            RecipeCategoryId = 2,
                            Source = "https://www.",
                            Time = 30,
                            Title = "Example recipe 2",
                            Vegetarian = false
                        });
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.RecipeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "B",
                            Name = "Backwaren"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "F",
                            Name = "Frühstück"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "H",
                            Name = "Hauptgericht"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Sa",
                            Name = "Salat"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "Su",
                            Name = "Sauce"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "Sp",
                            Name = "Suppen"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "V",
                            Name = "Vorspeisen & Antipasti"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "D",
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.RecipeGroceryItem", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroceryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("Measurementunit")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeId", "GroceryItemId");

                    b.HasIndex("GroceryItemId");

                    b.ToTable("RecipeGroceryItems");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            GroceryItemId = 1,
                            Amount = 5.0,
                            Measurementunit = 0
                        },
                        new
                        {
                            RecipeId = 1,
                            GroceryItemId = 3,
                            Amount = 5.0,
                            Measurementunit = 1
                        });
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.GroceryItem", b =>
                {
                    b.HasOne("RecipeManagerWeb.Models.GroceryCategory", "GroceryCategory")
                        .WithMany("GroceryItems")
                        .HasForeignKey("GroceryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryCategory");
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.InstructionStep", b =>
                {
                    b.HasOne("RecipeManagerWeb.Models.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.Recipe", b =>
                {
                    b.HasOne("RecipeManagerWeb.Models.RecipeCategory", "RecipeCategory")
                        .WithMany()
                        .HasForeignKey("RecipeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeCategory");
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.RecipeGroceryItem", b =>
                {
                    b.HasOne("RecipeManagerWeb.Models.GroceryItem", "GroceryItem")
                        .WithMany()
                        .HasForeignKey("GroceryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeManagerWeb.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.GroceryCategory", b =>
                {
                    b.Navigation("GroceryItems");
                });

            modelBuilder.Entity("RecipeManagerWeb.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
